version: “3.2”

services:

  keycloak-0:

    image: "hakimnorizman/keycloak-clustered:latest"
    environment:
      KEYCLOAK_USER: keycloak
      KEYCLOAK_PASSWORD: password
      DB_VENDOR: mariadb
      DB_ADDR: 192.168.1.1
      DB_PORT: 3306
      DB_DATABASE: KEYCLOAK01
      DB_USER: root
      DB_PASSWORD: password
	  PROXY_ADDRESS_FORWARDING: "true"
      JGROUPS_DISCOVERY_EXTERNAL_IP: 192.168.1.2
      JGROUPS_DISCOVERY_PROTOCOL: TCPPING
      JGROUPS_DISCOVERY_PROPERTIES: initial_hosts="192.168.1.2[7600]"
	  CACHE_OWNERS_COUNT: 2
	  CACHE_OWNERS_AUTH_SESSIONS_COUNT: 2
    restart: always
    ports:
      - "8080:8080"
      - "7600:7600"
